site_name: kiara
repo_url: https://github.com/DHARPA-project/kiara
site_description: Documentation for the Kiara project
site_url: https://dharpa.org/kiara_documentation/
site_author: Markus Binsteiner
docs_dir: docs
site_dir: build/site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite:
    guess_lang: false
- toc:
    permalink: true
    toc_depth: 3
- pymdownx.snippets:
    base_path: docs
- pymdownx.highlight
- pymdownx.superfences

#nav:
#- Home: index.md
#- Install: install.md
#- Usage:
#    - Overview: usage/index.md
#    - Getting started: usage/getting_started.md
#    - Running modules: usage/running_modules.md
#    - Data: usage/data.md
#    - Modules & Pipelines: usage/module_info.md
#    - Writing modules: usage/writing_modules_guide.md
#- Modules:
#    - Overview: modules/index.md
#    - Core modules: modules/core_modules.md
#    - Pipeline modules: modules/pipeline_modules.md
#- Workflows:
#    - Overview: workflows/index.md
#- Data:
#    - Overview: data/index.md
#    - Data registry: data/registry.md
#    - Tables:
#        - Overview: data/tables/index.md
#        - filtering: data/tables/filtering.md
#- Development:
#    - Overview: development/index.md
#    - Development environment: development/environment.md
#    - Module discovery: development/module_discovery.md
#    - Executing modules: development/executing_modules.md
#    - Pipeline controllers: development/pipeline_controllers.md
#    - Workflows: development/workflows.md
#    - Entities:
#      - Overview: development/entities/index.md
#      - Values / Data: development/entities/values.md
#      - Modules / Pipelines: development/entities/modules.md
#      - Events: development/entities/events.md

extra:
  version:
    provider: mike

plugins:
- search
- mknotebooks
- awesome-pages
#- mkdocstrings:
#    default_handler: python
#    watch:
#      - "src"
#- frkl-docgen:
#    main_module: "kiara_documentation"
- macros:
   modules:
     - kiara.doc.mkdocs_macros_cli
     - kiara.doc.mkdocs_macros_kiara
#- gen-files:
#    scripts:
#      - scripts/documentation/gen_module_doc.py
