site_name: kiara
repo_url: https://github.com/DHARPA-project/kiara
site_description: Documentation for the Kiara project
site_url: https://dharpa.org/kiara.documentation/
site_author: Markus Binsteiner
docs_dir: docs
site_dir: build/site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.tabs.link
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - navigation.expand

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite:
    guess_lang: false
- toc:
    permalink: true
    toc_depth: 3
- pymdownx.snippets:
    base_path: docs
- pymdownx.highlight
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: "!!python/name:pymdownx.superfences.fence_code_format"

extra:
  version:
    provider: mike
#    default: latest
plugins:
- search
- mknotebooks
- awesome-pages
- social
- macros:
   modules:
     - kiara.doc.mkdocs_macros_cli
     - kiara.doc.mkdocs_macros_kiara
#- gen-files:
#    scripts:
#      - scripts/documentation/gen_module_doc.py
