name: "linux tests and documentation builds for 'kiara_documentation'"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

  build-docs:
    name: build documentation
    if: ${{ github.ref == 'refs/heads/develop' }} || ${{ github.ref == 'refs/heads/main' }} || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('requirements.txt') }}
      - name: install git versions of the main requirements
        run: pip install --extra-index-url https://gitlab.com/api/v4/projects/25344049/packages/pypi/simple -r requirements.txt
      - name: install kiara_documentation
        run: pip install -U --pre  --extra-index-url https://gitlab.com/api/v4/projects/25344049/packages/pypi/simple --extra-index-url https://pypi.fury.io/dharpa/ .[all,dev_documentation]
      - name: create an entry in the data store
        run: KIARA_DATA_STORE="/tmp/data_store_3/" kiara run --output format=silent --save table=example.table table.import.from_local_file path=docs/example_data/JournalEdges1902.csv
      - name: create documentation
        run: FAIL_DOC_BUILD_ON_ERROR=true make docs
      - name: deploy documentation to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/site

#  release_package:
#    name: release python package to gemfury
#    if: ${{ github.ref == 'refs/heads/develop' }} || ${{ github.ref == 'refs/heads/main' }} || startsWith(github.ref, 'refs/tags/')
#    runs-on: ubuntu-latest
#    env:
#        GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
#    steps:
#      - name: Set up Python 3.9.1
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9.1
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: install kiara
#        run: pip install -U --extra-index-url https://gitlab.com/api/v4/projects/25344049/packages/pypi/simple --extra-index-url https://pypi.fury.io/dharpa/ -e .[all]
#      - name: install 'wheel' package
#        run: pip install -U wheel
#      - name: create packages
#        run: python setup.py sdist bdist_wheel
#      - name: upload source package
#        run: curl -F package=@$(ls dist/kiara*.tar.gz) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/
#      - name: upload wheel
#        run: curl -F package=@$(ls dist/kiara*.whl) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/
